# Generated by Django 5.2.12 on 2026-10-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0008_validate_birthday_age'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='birthday',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'birthday'), name='unique_birthday_person'),
        ),
    ]
