# Generated by Django 5.2.12 on 2026-10-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0009_birthday_unique_birthday_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='image',
            field=models.ImageField(blank=True, upload_to='birthdays_images/', verbose_name='Фото'),
        ),
    ]
